// examples/react-spa-npm/src/App.tsx
import { useAuth0 } from '@auth0/auth0-react';
import { Auth0ComponentProvider } from '@auth0/universal-components-react/spa';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Routes, Route, Navigate } from 'react-router-dom';

import { Navbar } from './components/nav-bar';
import { Sidebar } from './components/side-bar';
import ConnectedAccountsPage from './views/connected-accounts-page';
import DomainManagementPage from './views/domain-management-page';
import HomePage from './views/home-page';
import MemberDetailPage from './views/member-detail-page';
import MemberManagementPage from './views/member-management-page';
import MFAPage from './views/mfa-page';
import PasskeyPage from './views/passkey-page';
import OrganizationManagementPage from './views/organization-management-page';
import ProfilePage from './views/profile-page';
import SsoProviderCreatePage from './views/sso-provider-create-page';
import SsoProviderEditPage from './views/sso-provider-edit-page';
import SsoProviderPage from './views/sso-provider-page';
import { useDarkMode } from './hooks/use-dark-mode';

// Protected Route wrapper
const ProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated, isLoading } = useAuth0();

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-gray-600">Loading...</div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  return <>{children}</>;
};

function AppContent() {
  const { isAuthenticated } = useAuth0();

  return (
    <div className="min-h-screen bg-background" data-theme="default">
      <Navbar />
      {isAuthenticated && <Sidebar />}
      <main className={`pt-16 ${isAuthenticated ? 'ml-64' : ''}`}>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route
            path="/profile"
            element={
              <ProtectedRoute>
                <ProfilePage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/mfa"
            element={
              <ProtectedRoute>
                <MFAPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/passkeys"
            element={
              <ProtectedRoute>
                <PasskeyPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/connected-accounts"
            element={
              <ProtectedRoute>
                <ConnectedAccountsPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/organization-management"
            element={
              <ProtectedRoute>
                <OrganizationManagementPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/sso-providers"
            element={
              <ProtectedRoute>
                <SsoProviderPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/sso-provider/create"
            element={
              <ProtectedRoute>
                <SsoProviderCreatePage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/sso-provider/edit/:id"
            element={
              <ProtectedRoute>
                <SsoProviderEditPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/domain-management"
            element={
              <ProtectedRoute>
                <DomainManagementPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/member-management/:user_id"
            element={
              <ProtectedRoute>
                <MemberDetailPage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/member-management"
            element={
              <ProtectedRoute>
                <MemberManagementPage />
              </ProtectedRoute>
            }
          />
        </Routes>
      </main>
    </div>
  );
}

function App() {
  const { i18n } = useTranslation();
  const isDarkMode = useDarkMode();

  return (
    <Auth0ComponentProvider
      i18n={{ currentLanguage: i18n.language }}
      themeSettings={{
        theme: 'default',
        mode: isDarkMode ? 'dark' : 'light',
      }}
    >
      <AppContent />
    </Auth0ComponentProvider>
  );
}

export default App;

// examples/vue/src/App.vue
<script setup lang="ts">
import { useAuth0 } from '@auth0/auth0-vue';
import { Auth0ComponentProvider } from '@auth0/universal-components-vue';

import NavBar from './components/NavBar.vue';
import SideBar from './components/SideBar.vue';

const { isLoading, isAuthenticated } = useAuth0();
</script>

<template>
  <Auth0ComponentProvider
    :auth-details="{
      domain: 'devex.ca.auth0.com'
    }"
    :i18n="{ currentLanguage: 'en' }"
    :theme-settings="{
      theme: 'default',
      mode: 'light',
    }"
  >
    <div class="min-h-screen" data-theme="default">
      <NavBar />
      <SideBar v-if="isAuthenticated" />
      <main :class="['pt-16', isAuthenticated ? 'ml-64' : '']">
        <div v-if="isLoading" class="flex min-h-screen items-center justify-center">
          <div class="text-gray-600">Loading...</div>
        </div>
        <RouterView v-else />
      </main>
    </div>
  </Auth0ComponentProvider>
</template>
